name: Deploy SmartHome web
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "15"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.3
      - name: Install NPM dependencies
        run: npm ci
      - name: Rebuild node sass
        run: npm rebuild node-sass
      - name: Build the project
        run: npm run build
      - name: Replace SMARTHOME_BASE_URL
        run: "sed -i -e \"s#SMARTHOME_BASE_URL: '.*'#SMARTHOME_BASE_URL: 'https://l0q0rm6p2d.execute-api.eu-west-3.amazonaws.com/dev'#g\" dist/config.js"
      - name: Init Terraform
        run: terraform -chdir=terraform init -backend-config="access_key=AKIARRPNAYUPDAUQOEMK" -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}"
      - name: Apply Terraform
        run: terraform -chdir=terraform apply -var secret_key="${{ secrets.AWS_SECRET_KEY }}" -auto-approve
